part of 'sport_labels.dart';

const Map<int, String> _labelsA = {
  1: 'Outdoor Running',
  2: 'Treadmill',
  3: 'Walking',
  4: 'Outdoor Cycling',
  5: 'Free Training',
  6: 'Pool Swimming',
  7: 'Open Water Swimming',
  8: 'Indoor Riding',
  9: 'Elliptical Machine',
  10: 'Mountaineering',
  11: 'Cross Country Running',
  12: 'Skiing',
  15: 'Outdoor Hiking',
  17: 'Tennis',
  18: 'Football',
  19: 'Ironman Triathlon',
  20: 'Compound Motion',
  21: 'Jump Rope',
  23: 'Rowing Machine',
  24: 'Indoor Fitness',
  40: 'Indoor Walking',
  41: 'Curling',
  42: 'Snowboarding',
  43: 'Alpine Skiing',
  44: 'Outdoor Skating',
  45: 'Indoor Skating',
  46: 'Cross-Country Skiing',
  47: 'Mountain Cycling',
  48: 'BMX',
  49: 'High Intensity Interval Training',
  50: 'Core Training',
  51: 'Mixed Aerobic',
  52: 'Strength Training',
  53: 'Stretching',
  54: 'Climber',
  55: 'Flexibility Training',
  57: 'Step Training',
  58: 'Stepper',
  59: 'Gymnastics',
  60: 'Yoga',
  61: 'Pilates',
  62: 'Surfing',
  63: 'Hunting',
  64: 'Fishing',
  65: 'Sailing',
  66: 'Outdoor Boating',
  67: 'Skateboard',
  68: 'Paddleboarding',
  69: 'Roller Skating',
  70: 'Rock Climbing',
  71: 'Ballet',
  72: 'Belly Dance',
  73: 'Square Dance',
  74: 'Street Dance',
  75: 'Ballroom Dance',
  76: 'Dance',
  77: 'Zumba',
  78: 'Cricket',
  79: 'Baseball',
  80: 'Bowling',
  81: 'Squash',
  82: 'Rugby',
  83: 'Golf',
  84: 'Golf Swing',
  85: 'Basketball',
  86: 'Softball',
  87: 'Gateball',
  88: 'Volleyball',
  89: 'Ping Pong',
  90: 'Hockey',
  91: 'Handball',
  92: 'Badminton',
  93: 'Archery',
  94: 'Equestrian Sports',
  95: 'Swordsmanship',
  96: 'Karate',
  97: 'Boxing',
  98: 'Judo',
  99: 'Wrestling',
  100: 'Tai Chi',
  101: 'Muay Thai',
  102: 'Taekwondo',
  103: 'Martial Arts',
  104: 'Free Fighting',
  105: 'Snowboarding',
  106: 'Kitesurfing',
  108: 'Stair Climbing',
  109: 'Fitness',
  110: 'Orienteering',
  111: 'Group Exercise',
  112: 'Latin Dance',
};
